### ISSUE TITLE
Missing PAM50_small_label_disc.nii.gz for testing with -ldisc 

### ISSUE THREAD

**Issue by jcohenadad** [sct-data/sct_testing_data#7]
When testing `sct_register_to_template -ldisc`, the file PAM50_small_label_disc.nii.gz is missing.

**Comment by jcohenadad** [comment]
I created one using the command:
```
sct_label_utils -i PAM50_small_cord.nii.gz -create-seg 235,2:227,3:218,4:209,5:201,6:193,7:184,8:173,9:162,10:150,11:138,12:126,13:113,14:99,15:86,16:72,17:58,18:42,19 -o PAM50_small_label_disc.nii.gz
```

Note: with specifying labels above 19, I got the following error:
~~~
sct_label_utils -i PAM50_small_cord.nii.gz -create-seg 235,2:227,3:218,4:209,5:201,6:193,7:184,8:173,9:162,10:150,11:138,12:126,13:113,14:99,15:86,16:72,17:58,18:42,19:27,20 -o PAM50_small_label_disc.nii.gz

--
Spinal Cord Toolbox (git-jca/3300-label-rpi-890c90f881e30c270461f3a23b7a1c582d06a5a8*)

sct_label_utils -i PAM50_small_cord.nii.gz -create-seg 235,2:227,3:218,4:209,5:201,6:193,7:184,8:173,9:162,10:150,11:138,12:126,13:113,14:99,15:86,16:72,17:58,18:42,19:27,20 -o PAM50_small_label_disc.nii.gz
--

/Users/julien/code/sct/python/envs/venv_sct/lib/python3.6/site-packages/scipy/ndimage/measurements.py:1391: RuntimeWarning: invalid value encountered in double_scalars
  for dir in range(input.ndim)]
Traceback (most recent call last):
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_label_utils.py", line 413, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_label_utils.py", line 267, in main
    out = sct_labels.create_labels_along_segmentation(img, labels)
  File "/Users/julien/code/sct/spinalcordtoolbox/labels.py", line 130, in create_labels_along_segmentation
    x, y = int(np.round(x)), int(np.round(y))
ValueError: cannot convert float NaN to integer
~~~

Probably because the segmentation doesn't go that down.
